//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the arm_autopilot package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __arm_autopilot__AUTOPILOTPIDCONFIG_H__
#define __arm_autopilot__AUTOPILOTPIDCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace arm_autopilot
{
  class AutoPilotPIDConfigStatics;

  class AutoPilotPIDConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(AutoPilotPIDConfig &config, const AutoPilotPIDConfig &max, const AutoPilotPIDConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const AutoPilotPIDConfig &config1, const AutoPilotPIDConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, AutoPilotPIDConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const AutoPilotPIDConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AutoPilotPIDConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const AutoPilotPIDConfig &config) const = 0;
      virtual void getValue(const AutoPilotPIDConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T AutoPilotPIDConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T AutoPilotPIDConfig::* field;

      virtual void clamp(AutoPilotPIDConfig &config, const AutoPilotPIDConfig &max, const AutoPilotPIDConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const AutoPilotPIDConfig &config1, const AutoPilotPIDConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, AutoPilotPIDConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const AutoPilotPIDConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AutoPilotPIDConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const AutoPilotPIDConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const AutoPilotPIDConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, AutoPilotPIDConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, AutoPilotPIDConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<AutoPilotPIDConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(AutoPilotPIDConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Calibration"==(*_i)->name){Calibration = boost::any_cast<bool>(val);}
        if("Color"==(*_i)->name){Color = boost::any_cast<int>(val);}
        if("Hmin"==(*_i)->name){Hmin = boost::any_cast<int>(val);}
        if("Smin"==(*_i)->name){Smin = boost::any_cast<int>(val);}
        if("Vmin"==(*_i)->name){Vmin = boost::any_cast<int>(val);}
        if("Hmax"==(*_i)->name){Hmax = boost::any_cast<int>(val);}
        if("Smax"==(*_i)->name){Smax = boost::any_cast<int>(val);}
        if("Vmax"==(*_i)->name){Vmax = boost::any_cast<int>(val);}
        if("scale"==(*_i)->name){scale = boost::any_cast<int>(val);}
        if("Kp"==(*_i)->name){Kp = boost::any_cast<double>(val);}
        if("Ki"==(*_i)->name){Ki = boost::any_cast<double>(val);}
        if("Kd"==(*_i)->name){Kd = boost::any_cast<double>(val);}
        if("linear"==(*_i)->name){linear = boost::any_cast<double>(val);}
        if("LaserAngle"==(*_i)->name){LaserAngle = boost::any_cast<int>(val);}
        if("ResponseDist"==(*_i)->name){ResponseDist = boost::any_cast<double>(val);}
      }
    }

    bool Calibration;
int Color;
int Hmin;
int Smin;
int Vmin;
int Hmax;
int Smax;
int Vmax;
int scale;
double Kp;
double Ki;
double Kd;
double linear;
int LaserAngle;
double ResponseDist;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Calibration;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Color;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Hmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Smin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Vmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Hmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Smax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Vmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int scale;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double Kp;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double Ki;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double Kd;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double linear;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LaserAngle;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ResponseDist;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("AutoPilotPIDConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const AutoPilotPIDConfig &__max__ = __getMax__();
      const AutoPilotPIDConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const AutoPilotPIDConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const AutoPilotPIDConfig &__getDefault__();
    static const AutoPilotPIDConfig &__getMax__();
    static const AutoPilotPIDConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const AutoPilotPIDConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void AutoPilotPIDConfig::ParamDescription<std::string>::clamp(AutoPilotPIDConfig &config, const AutoPilotPIDConfig &max, const AutoPilotPIDConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class AutoPilotPIDConfigStatics
  {
    friend class AutoPilotPIDConfig;

    AutoPilotPIDConfigStatics()
    {
AutoPilotPIDConfig::GroupDescription<AutoPilotPIDConfig::DEFAULT, AutoPilotPIDConfig> Default("Default", "", 0, 0, true, &AutoPilotPIDConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Calibration = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Calibration = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Calibration = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<bool>("Calibration", "bool", 0, "color calibration", "", &AutoPilotPIDConfig::Calibration)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<bool>("Calibration", "bool", 0, "color calibration", "", &AutoPilotPIDConfig::Calibration)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Color = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Color = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Color = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Color", "int", 0, "A size parameter which is edited via an enum", "{'enum': [{'name': 'red', 'type': 'int', 'value': 0, 'srcline': 7, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'first data', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'green', 'type': 'int', 'value': 1, 'srcline': 8, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'two data', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'blue', 'type': 'int', 'value': 2, 'srcline': 9, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'three datat', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'yellow', 'type': 'int', 'value': 3, 'srcline': 10, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'four data', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set size'}", &AutoPilotPIDConfig::Color)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Color", "int", 0, "A size parameter which is edited via an enum", "{'enum': [{'name': 'red', 'type': 'int', 'value': 0, 'srcline': 7, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'first data', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'green', 'type': 'int', 'value': 1, 'srcline': 8, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'two data', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'blue', 'type': 'int', 'value': 2, 'srcline': 9, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'three datat', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'yellow', 'type': 'int', 'value': 3, 'srcline': 10, 'srcfile': '/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg', 'description': 'four data', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set size'}", &AutoPilotPIDConfig::Color)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Hmin = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Hmin", "int", 0, "Hmin in HSV", "", &AutoPilotPIDConfig::Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Hmin", "int", 0, "Hmin in HSV", "", &AutoPilotPIDConfig::Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Smin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Smin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Smin = 85;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Smin", "int", 0, "Smin in HSV", "", &AutoPilotPIDConfig::Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Smin", "int", 0, "Smin in HSV", "", &AutoPilotPIDConfig::Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Vmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Vmin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Vmin = 126;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Vmin", "int", 0, "Vmin in HSV", "", &AutoPilotPIDConfig::Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Vmin", "int", 0, "Vmin in HSV", "", &AutoPilotPIDConfig::Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Hmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Hmax = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Hmax = 9;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Hmax", "int", 0, "Hmax in HSV", "", &AutoPilotPIDConfig::Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Hmax", "int", 0, "Hmax in HSV", "", &AutoPilotPIDConfig::Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Smax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Smax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Smax = 253;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Smax", "int", 0, "Smax in HSV", "", &AutoPilotPIDConfig::Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Smax", "int", 0, "Smax in HSV", "", &AutoPilotPIDConfig::Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Vmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Vmax", "int", 0, "Vmax in HSV", "", &AutoPilotPIDConfig::Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("Vmax", "int", 0, "Vmax in HSV", "", &AutoPilotPIDConfig::Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.scale = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.scale = 1000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.scale = 1000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("scale", "int", 0, "scale", "", &AutoPilotPIDConfig::scale)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("scale", "int", 0, "scale", "", &AutoPilotPIDConfig::scale)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Kp = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Kp = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Kp = 30.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("Kp", "double", 0, "Kp in PID", "", &AutoPilotPIDConfig::Kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("Kp", "double", 0, "Kp in PID", "", &AutoPilotPIDConfig::Kp)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Ki = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Ki = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("Ki", "double", 0, "Ki in PID", "", &AutoPilotPIDConfig::Ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("Ki", "double", 0, "Ki in PID", "", &AutoPilotPIDConfig::Ki)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Kd = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Kd = 100.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Kd = 60.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("Kd", "double", 0, "Kd in PID", "", &AutoPilotPIDConfig::Kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("Kd", "double", 0, "Kd in PID", "", &AutoPilotPIDConfig::Kd)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.linear = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.linear = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.linear = 0.25;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("linear", "double", 0, "linear", "", &AutoPilotPIDConfig::linear)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("linear", "double", 0, "linear", "", &AutoPilotPIDConfig::linear)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LaserAngle = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LaserAngle = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LaserAngle = 30;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("LaserAngle", "int", 0, "LaserAngle", "", &AutoPilotPIDConfig::LaserAngle)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<int>("LaserAngle", "int", 0, "LaserAngle", "", &AutoPilotPIDConfig::LaserAngle)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ResponseDist = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ResponseDist = 8.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ResponseDist = 0.55;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("ResponseDist", "double", 0, "ResponseDist", "", &AutoPilotPIDConfig::ResponseDist)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutoPilotPIDConfig::AbstractParamDescriptionConstPtr(new AutoPilotPIDConfig::ParamDescription<double>("ResponseDist", "double", 0, "ResponseDist", "", &AutoPilotPIDConfig::ResponseDist)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(AutoPilotPIDConfig::AbstractGroupDescriptionConstPtr(new AutoPilotPIDConfig::GroupDescription<AutoPilotPIDConfig::DEFAULT, AutoPilotPIDConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<AutoPilotPIDConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<AutoPilotPIDConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<AutoPilotPIDConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    AutoPilotPIDConfig __max__;
    AutoPilotPIDConfig __min__;
    AutoPilotPIDConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const AutoPilotPIDConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static AutoPilotPIDConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &AutoPilotPIDConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const AutoPilotPIDConfig &AutoPilotPIDConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const AutoPilotPIDConfig &AutoPilotPIDConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const AutoPilotPIDConfig &AutoPilotPIDConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<AutoPilotPIDConfig::AbstractParamDescriptionConstPtr> &AutoPilotPIDConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<AutoPilotPIDConfig::AbstractGroupDescriptionConstPtr> &AutoPilotPIDConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const AutoPilotPIDConfigStatics *AutoPilotPIDConfig::__get_statics__()
  {
    const static AutoPilotPIDConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = AutoPilotPIDConfigStatics::get_instance();

    return statics;
  }

//#line 7 "/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg"
      const int AutoPilotPID_red = 0;
//#line 8 "/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg"
      const int AutoPilotPID_green = 1;
//#line 9 "/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg"
      const int AutoPilotPID_blue = 2;
//#line 10 "/root/yahboomcar_ws/src/arm_autopilot/cfg/autopilot.cfg"
      const int AutoPilotPID_yellow = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __AUTOPILOTPIDRECONFIGURATOR_H__
