arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm_joint1
    - arm_joint2
    - arm_joint3
    - arm_joint4
    - arm_joint5
  gains:
    arm_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1